.pre-commit-config.yaml * added
.shellcheckrc
* added

Fixed several linting issues

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,15 +1,14 @@
 #!/bin/bash
 
 exec < /dev/tty
-echo -n 'run `check-scripts`? [Y/n] '; read
+# shellcheck disable=SC2016
+echo -n 'run `check-scripts`? [Y/n] '; read -r
 
 [[ "$REPLY" =~ [Nn] ]] || {
    # run the `check-scripts` function, which should already be sourced
-   check-scripts
-
-   [[ $? -eq 0 ]] || {
+   check-scripts || {
       echo
-      echo -n "continue committing, despite the above errors? [y/N] "; read
+      echo -n "continue committing, despite the above errors? [y/N] "; read -r
       [[ "$REPLY" =~ [Yy] ]] || exit 1
    }
 }
