.bashrc.d/aliases_general * added example sudoers lines
.bashrc.d/functions/_find_unscoped_vars
* added more robust code for finding and presenting improperly scoped variables across multiple files

.bashrc.d/functions/archive-emails
* added more robust code for accurately calculating time frames for which to show emails

.bashrc.d/functions/clipit-copy
* updated to properly scope variables

.bashrc.d/functions/convert-timestamp-to-date
* updated to properly scope variables

.bashrc.d/functions/copy-skey
* updated to properly scope variables

.gitconfig
* updated the `ci` alias to correctly handle arguments

.gitconfig.d/git-sync.sh
* updated to provide more control around stashing to be more compatible with being run via cronjob vs. manually

.tmux.conf
* added a comment noting the unfortunate behavior in which tmux reads and executes its config file in full before creating a session leading to errors

etc/logrotate.d/chrome-history
* updated rotation count to be 520 weeks (~10 years) to ensure the history doesn't destroy old files too often

etc/sudoers
* added a comment with example lines for enabling commands to be run without prompting for the password

var/spool/cron/crontabs/username
* updated to include examples of cronjobs for starting and stopping a service

diff --git a/.bashrc.d/functions/_find_unscoped_vars b/.bashrc.d/functions/_find_unscoped_vars
--- a/.bashrc.d/functions/_find_unscoped_vars
+++ b/.bashrc.d/functions/_find_unscoped_vars
@@ -1,12 +1,30 @@
 #!/bin/bash
 
 _find_unscoped_vars() {
-   local file
+   local files="${@:-$HOME/.bashrc.d/functions/*}"
    local unscoped_vars
+   local var_chars="[a-zA-Z_0-9]"
+   local var_assignment_chars="([][()*/%+&^|<>-]|<<|>>)"
 
-   for file in $HOME/.bashrc.d/functions/*; do
-      for var in $(grep -hoP '^ *\K[^][ ]+=' "$file" | cut -d= -f1); do
-         grep -q "local $var" "$file" || unscoped_vars+=("$(cat -n "$file" | sed -rne "s;^\s+([0-9]+)\s+("$var")=.*;\1:\2;p" | head -n1)")
+   for file in $files; do
+      [[ -f "$file" && -r "$file" ]] || {
+         echo "can't read file: '$file'"
+         echo "skipping..."
+         continue
+      }
+
+      # grab all vars from the given file, including those with special assignment operators
+      # this assumes Bash is the language used, and there could be issues with arrays
+      for var in $(sed -rne "s;^\s*([^ #=[]$var_chars+)$var_assignment_chars?=.*;\1;p" "$file" | sort -u); do
+#         echo "var = '$var'"
+         # ensure the variable is locally defined
+         egrep -q "((declare|typeset)( -[^g])?|local) $var" "$file" || {
+            # if it's not locally defined
+#            echo [[ ${unscoped_vars[*]} =~ $var ]]
+            [[ ${unscoped_vars[*]} =~ $var ]] ||
+            # and it's not already in the unscoped_vars array, then add it to the array
+            unscoped_vars+=("$(cat -n "$file" | sed -rne "s;^\s+([0-9]+)\s+("$var")\+?=.*;\1:\2;p" | head -n1)")
+         }
       done
 
       if [[ ${#unscoped_vars[*]} -gt 0 ]]; then
@@ -14,7 +32,7 @@ _find_unscoped_vars() {
 
          for i in ${unscoped_vars[*]}; do
             echo "$i"
-         done
+         done | sort -nu
 
          echo
 
