.bashrc.d/functions/_print_var_vals * fixed so it doesn't bomb out if given an unset or non-variable
.bashrc.d/functions/_verify_reqs
* fixed a bug in which failures weren't correctly listed

.bashrc.d/functions/compact_history
* updated the regex removal line to account for leading and trailing whitespace

.bashrc.d/functions/diff-home-files
* updated to build a more complete list of files to compare

.bashrc.d/functions/verbose
- removed teeing to a file

.bashrc.d/functions/yessh
* updated to not bomb out if ~/.bashrc.d/remote/* doesn't exist

.bashrc.d/remote/remote_base
+ added a note regarding the purpose of this file

.docker/config.json
+ added

.vimrc
+ added some config directives

CONTRIBUTING.md
+ added

diff --git a/.bashrc.d/functions/_verify_reqs b/.bashrc.d/functions/_verify_reqs
--- a/.bashrc.d/functions/_verify_reqs
+++ b/.bashrc.d/functions/_verify_reqs
@@ -35,6 +35,7 @@ _verify_reqs() {
       echo "function: ${FUNCNAME[1]}"
       echo "line: ${BASH_LINENO[0]}";
    fi
+
    declare -a failures
 
    for req in ${requirements[*]}; do
@@ -48,7 +49,7 @@ _verify_reqs() {
       [[ "$needed_version" == "$req" ]] && needed_version="$actual_version"
 
       # make sure both the required command, as well as the version, if specified, are what we actually have
-      { type -t "$req" &>/dev/null && [[ "$needed_version" == "$actual_version" ]]; }|| failures+=("$req")
+      { type -t "$req" &>/dev/null && [[ "$needed_version" == "$actual_version" ]]; } || failures+=("$req")
    done
 
    if [[ -n ${failures[*]} ]]; then
@@ -56,7 +57,7 @@ _verify_reqs() {
       echo
 
       for failure in ${failures[*]}; do
-         echo "* $req"
+         echo "* $failure"
       done
 
       echo
