.bashrc * updated `$PROMPT_COMMAND`
.bashrc.d/00_vars
* added `$MANPAGER`
* updated `$SYSTEMD_LESS` to not chop off lines

.bashrc.d/aliases_general
* updated `edit-history` alias to no longer unset or set append-only mode

.bashrc.d/base
* added a comment about `.apple_keyboard_mod.rc` adding noticeable lag time when sourcing in a new terminal

.bashrc.d/functions/bar_graph
* added a comment with an `awk` command that can accomplish a similar bar graph

.bashrc.d/functions/get_creds
* added some TODOs and FIXMEs

.bashrc.d/functions/mysql
* updated verbosity level for outputting the `mysql` command that's run

.gitconfig
* fixed `git dff` to properly account for `$GIT_PREFIX`

.tmux.conf
* updated status line format and colors
* replaced shorthand aliases for variables

.vimrc
* added a handy `:exe` command

diff --git a/.bashrc.d/functions/get_creds b/.bashrc.d/functions/get_creds
--- a/.bashrc.d/functions/get_creds
+++ b/.bashrc.d/functions/get_creds
@@ -1,6 +1,10 @@
 #!/bin/bash
 
 get_creds() {
+   # TODO:
+   # * refresh tokens periodically
+   # * shell autocomplete keys/templates
+
    # this function retrieves creds in a standardized format either retrieved from LastPass (as done initially)
    # or from a local file saved from a previous run of this function
 
@@ -283,6 +287,8 @@ get_creds() {
          entry_array[$i]="$(echo "$contents" | grep -ioP "^$pattern\K.*" | sed -e "s;[\"'];;g" | head -n1)"
 
          # attempt to retrieve the values from LastPass if the local cache is incomplete
+         # FIXME: find missing templates with this and automatically create those templates:
+         # for file in ~/digitalocean/.creds/keys/*; do orig_file="$file"; file="${file/keys/templates}"; [[ -f "$file" ]] || { echo "$file template missing"; sed -rne 's;^([^=]+\=["'\''])[^"'\'']+(["'\''])$;\1\2;p' "$orig_file"; echo; }; done
          if [[ $is_from_file -eq 1 && -z "${entry_array[$i]}" ]]; then
             # one of the cached entries is empty, and we cannot trust the
             # overall accuracy of the local cache, so re-run this after
