.bashrc * fix linting issues
.bashrc.d/00_vars
* update `$LESS` value

.bashrc.d/functions/convert-timestamp-to-date
* add timestamp conversion info in comments

.bashrc.d/functions/list-to-quoted-csv
* add support to quoting function for non-quote characters (e.g., parentheses, curl braces, etc.)

.bashrc.d/functions_sec
* add support for different complemented character sets for generated passwords

.bashrc.d/remote/README.md
* update information on what the remote config does

.gitconfig
* add "tabspace" filters

.gitconfig.d/git-sync.sh
* fix linting issues

.vimrc
* update textwidth for "gitcommit" type files
* mention several potentially useful plugins

var/spool/cron/crontabs/username
* add cron format reference comments

diff --git a/.bashrc.d/functions/list-to-quoted-csv b/.bashrc.d/functions/list-to-quoted-csv
--- a/.bashrc.d/functions/list-to-quoted-csv
+++ b/.bashrc.d/functions/list-to-quoted-csv
@@ -8,9 +8,19 @@ list-to-quoted-csv() {
 	EOF
 
    local input="$(_get_stdin "$1")"
-   local no_quotes="$2"
-   local quotes='"'
+   local start_quote="${2:-}"
+   [[ "${#start_quote}" -ne 1 ]] || {
+      echo "error: must be a single character (excluding an escape)"
+      return 1
+   }
+   [[ "${start_quote}" =~ []}\)] ]] && start_quote="$(echo "${start_quote}" | tr '}])' '{[(')"
+   local end_quote="${start_quote}"
+#   echo "input = '${input}'"
+#   echo "start_quote = '${start_quote}'"
+#   echo "end_quote = '${end_quote}'"
+   [[ "${start_quote}" =~ [[{\(] ]] && end_quote="$(echo "${start_quote}" | tr '{[(' '}])')"
 
-   [[ "$no_quotes" =~ nq ]] && quotes=""
-   echo "$input" | sed -rne "s;^.*$;${quotes}&${quotes}\,;gp" | tr -d '\n' | sed -re 's;(^,|,$);;g' -e 's;$;\n;'
+
+#   echo "$input" | sed -rne "s;^.*$;${quotes}&${quotes}\,;gp" | tr -d '\n' | sed -re 's;(^,|,$);;g' -e 's;$;\n;'
+   echo "$input" | sed -rne "s;^.*$;${start_quote}&${end_quote};gp" | paste -sd,
 }
