.bashrc.d/functions/diff-home-files * enabled skipping files
.bashrc.d/functions/time-between-now-and
* updated logic to properly calculate days, hours, minutes, and seconds

.bashrc.d/functions/yessh
* fixed an issue when ssh'ing into hosts that don't have `bzip2` installed by default, like CentOS

.bashrc.d/remote/remote_base
* improved logic in run-check() for running check commands

.gitconfig
* updated `pushall` and `pushallf` aliases to ask before pushing to `master`
* fixed an issue with `changelog` alias regarding formatting of lines following date lines

.tmux.conf
* added commented out code that may fix the issue with tmux tabs not automatically getting renamed

.vimrc
* set formatting options explicitly so they're not as easily overriden

diff --git a/.bashrc.d/remote/remote_base b/.bashrc.d/remote/remote_base
--- a/.bashrc.d/remote/remote_base
+++ b/.bashrc.d/remote/remote_base
@@ -16,17 +16,33 @@ alias mtr='sudo mtr -s 1472 -i.1 -c1000'
 
 run-check() {
    local check_name="$1"
+   local sudo=
    local check_command
    local output
 
-   check_command="$(grep -ir "$check_name" /etc/nagios/nrpe* | cut -d= -f2)"
+   [[ "$1" =~ ^-s$ ]] && {
+      sudo="sudo"
+      check_name="$2"
+   }
+
+   check_command="$(grep -hir "\[$check_name\]" /etc/nagios/nrpe* | sed -rne 's;^command\[[^=]+=(.*);\1;p')"
 
    [[ "$check_command" ]] || {
       echo "error: command not found: '$check_command'"
+      echo "available checks:"
+      grep --color=never --directories=skip -P '^command\[' /etc/nagios/nrpe*
       return 1
    }
 
-   output="$(bash "$check_command" 2>&1)"
+   [[ -x "${check_command%% *}" ]] || {
+      echo "error: command not executable: '$check_command'"
+      return 1
+   }
+
+   [[ "$sudo" ]] && echo -n "$sudo "
+   echo "$check_command"
+
+   output="$($sudo bash -c "$check_command" 2>&1)"
 
    [[ "$output" =~ Permission" "denied$ ]] && {
       # retry with sudo
