.bashrc.d/base * switched back to `tee` from `sponge` * added `mtr` to HISTIGNORE
.bashrc.d/functions_sec
* added `ssh_key_is_encrypted()`

.bashrc.d/remote/remote_base
* fixed source command to ensure it isn't going to recursively source

.gitconfig
* updated various aliases to support `main` branch
* added aliases to detect the main branch and main remote names

.gitconfig.d/git-sync.sh
* added support for `main` branch name
* added some checks and verbosity

etc/hosts
* added more domains to blacklist

diff --git a/.bashrc.d/functions_sec b/.bashrc.d/functions_sec
--- a/.bashrc.d/functions_sec
+++ b/.bashrc.d/functions_sec
@@ -126,3 +126,21 @@ generate_luks_keyfile() {
       echo "you must specify an output file!"
    fi
 }
+
+ssh_key_is_encrypted() {
+   local file="$1"
+
+   [[ -r "$file" ]] || {
+      echo "error: file unreadable or doesn't exist: '$file'"
+      return 2
+   }
+
+   grep -iq encrypted "$file" || {
+      if head -n1 "$file" | grep -iq openssh; then
+         { tail -n+2 "$file" | head -n-1 | base64 -d | strings | grep -iq bcrypt; } &&
+            return 0
+      else
+         return 1
+      fi
+   }
+}
