.bashrc.d/vars * renamed to be .bashrc.d/00_vars
.bashrc
* moved some content to .bashrc.d/base

.bashrc.d/aliases
- removed some outdated and unused aliases

.bashrc.d/functions
+ _print_var_vals(): added
  compact_history():
    + added support for an immutable history file
    + added support for removing history entries matching a given regex
    + added support for simulating a run

diff --git a/.bashrc.d/functions b/.bashrc.d/functions
--- a/.bashrc.d/functions
+++ b/.bashrc.d/functions
@@ -67,6 +67,26 @@ _verify_reqs() {
    fi
 }
 
+_print_var_vals() {
+
+   # takes all arguments and prints out their values (for debugging)
+   # this assumes all arguments are indeed variables
+   # any argumentsthat aren't variables, are unset, or have no assigned
+   # value are still accepted and simply printed to indicate no value
+
+   # input: a list of variable names
+   # output: the list of variable names, along with their values, if any
+
+   _verify_reqs <<-EOF || return 1
+   verbose
+	EOF
+
+   for i in $@; do
+      declare -n _variable="$i"
+      verbose 8 "$i = $_variable"
+   done
+}
+
 count-ips-from-tcpdump() {
    # used to determine source IPs possibly involved in server issues based on overall occurrence in total traffic
    # first run something like this on the server to get good sample data:
@@ -173,14 +193,13 @@ pushd() {
       while read line; do
           verbose 2 "line = '$line'"
           local path="${line#*$'\1'}"     # grab the path from the line
-          path="${path/\~/$HOME}"         # replace ~ with $HOME so 'realpath' doesn't complain
           local position="${line%$'\1'*}" # grab the position in the dir stack from the line
 
           dirstack["$(realpath "${path}")"]="$position"
           verbose 2 dirstack["$(realpath ${path})"]="$position"
           unset path
           unset position
-      done <<<$(dirs -v | sed -re "s;^ +([0-9]+) +(.*)$;\1\o1\2;") # delimite each field in the entry with octal 001
+      done <<<$(dirs -v -l | sed -re "s;^ +([0-9]+) +(.*)$;\1\o1\2;") # delimite each field in the entry with octal 001
 
       verbose 2 "[[ ${dirstack[$dir]} ]]"
 
@@ -568,8 +587,9 @@ verbose() {
             verbosity=7;;
          debug) # debug-level message
             verbosity=8;;
-           [0-9])
-            verbosity="$1";;
+           [0-9]*)
+            verbosity="$1"
+            [[ $verbosity -gt 8 ]] && verbosity=8;;
       esac
       shift
    fi
@@ -614,29 +634,93 @@ copy-skey() {
 }
 
 compact_history() {
+
    # remove all duplicates in the history file since HISTCONTROL=ignoreboth doesn't seem to work the current setup :/
+
+   # input: optional file to compact (expected to be in the typical history file format, including timestamps
+   # output: nothing on success, but the temporary file name for you to peruse if run with the simulate/dry-run option
+
+   _verify_reqs <<-EOF || return 1
+   verbose
+	EOF
+
+	local DRY_RUN=0
+	local VERBOSE=1
+	local HISTORY_FILE
+	local REMOVAL_REGEX
+
+   while [[ $# -ge 1 ]]; do
+      local arg="$1"
+      verbose 8 "arg = $arg"
+      case $arg in
+         -n|--dry-run)
+            DRY_RUN="1"
+            ;;
+         -r|--regex)
+            shift
+            REMOVAL_REGEX="$1"
+            ;;
+         *)
+            if [[ -s "$arg" ]]; then
+               HISTORY_FILE="$arg"
+            fi
+            ;;
+      esac
+      shift
+   done
+
+   HISTORY_FILE="${HISTORY_FILE:-$HOME/.bash_history}"
+   local HISTORY_FILE_BACKUP="${HISTORY_FILE}_$(date +'%F_%Hh%Mm%Ss').bak"
+   local TEMP_FILE="$(mktemp)"
+
+   _print_var_vals \
+    DRY_RUN \
+    VERBOSE \
+    HISTORY_FILE \
+    REMOVAL_REGEX
+   verbose 8
 
 #   cat ~/.bash_history | tr '\n' '^M' | sed -rne 's;^M(#[0-9]{10,11})^M([^^M]+);\1  \2^M;gp' | tr '^M' '\n' | egrep '^#[0-9]{10,11}' | sort -u -k 2 | sort | sed -rne 's;^(#[0-9]{10,11})   (.*)$;\1\n\2;p' >~/.bash_history.new
 #   sed -re 's;^(#[0-9]{10,11})$;\o0\1;' ~/.bash_history | tr '\n' '\1' | sed -rne 's;\o0(#[0-9]{10,11}[^\o0]+);\1\n;gp' | sort -uk2 | sort | tr -d '\n' | tr '\1' '\n' >~/.bash_history.new2
 #   sed -re 's;^(#[0-9]{10,11})$;\o0\1;' ~/.bash_history | tr '\n' '\1' | sed -rne 's;\o0([^\o0]+);\1\n;gp' | sort -uk2 | sort | tr -d '\n' | tr '\1' '\n' | less
 #   sed -re 's;^(#[0-9]{10,11})$;\o0\1;' ~/.bash_history | tr '\n' '\1' | sed -rne 's;\o0([^\o0]+);\1\n;gp' | sort -u -t$'\1' -k2 | sort | tr -d '\n' | tr '\1' '\n' | less
 
-   local history_file="$HOME/.bash_history"
-   local history_file_backup="${history_file}_$(date +'%F_%Hh%Mm%Ss').bak"
-   local temp_file="$(mktemp)"
-
    # we might be able to change the octal characters used here so we can utilize sort's '-z' option, but that might not be as portable
 
-   sed -re 's;^(#[0-9]{10,11})$;\o0\1;' "$history_file" | # replace start of lines with a null character (000 octal) so we know the start of a history entry (assuming with a timestamp)
+   sed -re 's;^(#[0-9]{10,11})$;\o0\1;' "$HISTORY_FILE" | # replace start of lines with a null character (000 octal) so we know the start of a history entry (assuming with a timestamp)
    tr '\n' '\1' |                                         # replace all newlines with a 001 octal character so we can keep track of where the newlines should later go, including in multi-line entries
    sed -rne 's;\o0([^\o0]+);\1\n;gp' |                    # re-insert newlines just at the end of each history entry so we can sort
    sort -u -t$'\1' -k2 |                                  # sort by command to remove duplicates
-   sort |                                                 # sort again—this time by timestamp
+   sort |                                                 # sort again—this time by timestamp, the original order of the entries
+   egrep -v $'\1'"$REMOVAL_REGEX"$'\1' |                  # remove all entries matching the provided regex, if any (this is safe to run, even if the regex isn't provided or is blank
    tr -d '\n' |                                           # remove the newlines we'd previously inserted so they don't double up
-   tr '\1' '\n' >"$temp_file"                             # re-insert all newlines that were there from the beginning
+   tr '\1' '\n' >"$TEMP_FILE"                             # re-insert all newlines that were there from the beginning
 
    # perform the actual move if the new temp file has data in it (after backing up the original history file)
-   [[ -s "$temp_file" ]] && mv "$history_file" "$history_file_backup" && mv "$temp_file" "$history_file" >/dev/null
+   if [[ -s "$TEMP_FILE" ]]; then
+      if [[ $DRY_RUN -eq 1 ]]; then
+         ls -halF "$TEMP_FILE"
+      else
+         local APPEND_ONLY=0
+
+         if lsattr -l "$HISTORY_FILE" | grep -qi append_only; then
+            verbose 0 "attempting to remove append-only mode for '$HISTORY_FILE'"
+            sudo chattr -a "$HISTORY_FILE"
+            APPEND_ONLY=1
+         fi
+
+         # move the new history file to the default one
+         mv "$HISTORY_FILE" "$HISTORY_FILE_BACKUP" &&
+          mv "$TEMP_FILE" "$HISTORY_FILE" >/dev/null
+
+         if [[ $APPEND_ONLY -eq 1 ]]; then
+            verbose 0 "attempting to re-apply append-only mode for '$HISTORY_FILE'"
+            sudo chattr +a "$HISTORY_FILE"
+         fi
+      fi
+   else
+      verbose 1 "error: '$TEMP_FILE' couldn't be made or is empty!"
+   fi
 }
 
 generate_luks_keyfile() {
