refactor: change back from matrix

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -43,7 +43,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       BASE_REF: ${{ steps.export_base_ref.outputs.BASE_REF }}
-      CHANGED_FILES: ${{ steps.changed_files.outputs.CHANGED_FILES }}
+      CHANGED_FILES: ${{ toJson(steps.changed_files.outputs.CHANGED_FILES) }}
     steps:
       - uses: actions/checkout@v3
         env:
@@ -116,11 +116,7 @@ jobs:
   check-readme:
     runs-on: ubuntu-latest
     needs: [get-changed-files]
-    if: contains(needs.get-changed-files.outputs.CHANGED_FILES, 'README.md.tpl')
-    strategy:
-      matrix:
-        file:
-          ${{ fromJson(needs.get-changed-files.outputs.CHANGED_FILES) }}
+    if: contains(needs.get-changed-files.outputs.CHANGED_FILES, '.md.tpl')
     steps:
       - uses: actions/checkout@v3
         env:
@@ -143,29 +139,46 @@ jobs:
           apt-get update &&
           apt-get install ${pkgs_to_install[*]}
 
+          #      - name: Install envsubst
+          #        # this is required when using nektos/act due to this sort of issue with
+          #        # act's ubuntu:latest image (it's still on 20.04):
+          #        if: env.ACT
+          #        run: |
+          #          declare -A pkgs_to_install=(
+          #          [envsubst]=gettext-base
+          #          [column]=bsdextrautils
+          #          )
+          #          for pkg in ${!pkgs_to_check[*]}; do
+          #             which "${pkg}" &>/dev/null && unset pkgs_to_install["${pkg}"]
+          #          done
+          #          apt-get update &&
+          #          apt-get install ${pkgs_to_install[*]}
+
       - name: Ensure Documentation Was Generated
-        if: endsWith(matrix.file, '.md.tpl')
         run: |
-          file="${{ matrix.file }}"
-          RENDERED_FILENAME="${file%%.tpl}"
-          if [[ -s "${RENDERED_FILENAME}" ]]; then
-            ORIG_CHECKSUM="$(md5sum "${RENDERED_FILENAME}")"
-            mv -v "${RENDERED_FILENAME}" "${RENDERED_FILENAME}.orig"
-            make readme
-            NEW_CHECKSUM="$(md5sum "${RENDERED_FILENAME}")"
-            [[ "${ORIG_CHECKSUM}" == "${NEW_CHECKSUM}" ]] || {
-              echo "error: ${RENDERED_FILENAME} was not generated"
-              echo
-              echo "Generate the documentation using this command, then commit and push:"
-              echo
-              echo "    make readme"
-              echo
-              exit 1
-            }
-          else
-            echo "error: ${RENDERED_FILENAME} doesn't exist or is empty"
-            exit 1
-          fi
+          make readme
+          git diff --exit-code
+          #          for file in $(echo ${{ needs.get-changed-files.outputs.CHANGED_FILES }} | jq -r '.[]'); do
+          #            echo "file = '$file'"
+          #            RENDERED_FILENAME="${file%%.tpl}"
+          #            if [[ -s "${RENDERED_FILENAME}" ]]; then
+          #              ORIG_CHECKSUM="$(md5sum "${RENDERED_FILENAME}")"
+          #              mv -v "${RENDERED_FILENAME}" "${RENDERED_FILENAME}.orig"
+          #              make readme
+          #              NEW_CHECKSUM="$(md5sum "${RENDERED_FILENAME}")"
+          #              [[ "${ORIG_CHECKSUM}" == "${NEW_CHECKSUM}" ]] || {
+          #                echo "error: ${RENDERED_FILENAME} was not generated"
+          #                echo
+          #                echo "Generate the documentation using this command, then commit and push:"
+          #                echo
+          #                echo "    make readme"
+          #                echo
+          #                exit 1
+          #              }
+          #            else
+          #              echo "error: ${RENDERED_FILENAME} doesn't exist or is empty"
+          #              exit 1
+          #            fi
 
   dump-env:
     # most of this inspired by:
